### ISSUE TITLE
Erlang flags

### ISSUE THREAD

**Issue by josevalim** [mroth/phoenix-showdown#1]
Curiosity: do you get a better performance by using these flags when starting Phoenix?

    elixir --erl "+K true +A 100" -pa _build/prod/consolidated -S mix phoenix.start

The first enables kernel pool and the other one increases the number of async threads. More info here: http://stackoverflow.com/questions/1182025/what-do-the-erlang-emulator-info-statements-mean

Sorry for being lazy and opening an issue instead of trying it myself but my machine handles half of the load of yours. :P

**Comment by mroth** [comment]
Hah, somehow I forgot to check this original issue when doing the new round of benchmarks and just found it again now.  Is it still relevant with Elixir 1.0.x and the latest Phoenix?  If so I'll certainly give it a try.

**Comment by josevalim** [comment]
Yes, they are relevant. If you have some time, just give it a quick try and see if you notice different results. I personally have not. :) Definitely not pressing.

**Comment by mroth** [comment]
Just tested and not noticing any significant change in casual benchmarking.  It's possible it makes a small difference but one that doesn't become apparent under this particular test.

But since you don't see anything either, I guess we can consider this closed for now.
