### ISSUE TITLE
Gin (go) implementation

### ISSUE THREAD

**Issue by ciarand** [mroth/phoenix-showdown#10]
Hey, this isn't a PR because I'm not sure if you want to add this code (because benchmark pissing contents are silly for the most part).

I added a different framework for Go, [Gin](//github.com/gin-gonic/gin), that seems to be performing better than Martini by a significant amount (2-3x on my machine, but ymmv). You can see my results in the fork's README [here](https://github.com/ciarand/phoenix-showdown/commit/1fbe6375d0dcb121168195c2fb81645c513635fa).

Thanks for putting this together btw, it's really interesting :+1:

**Comment by dimascyriaco** [comment]
I switched from Martini to Gin some time ago. The difference in performance was notable.

**Comment by mroth** [comment]
Hi @ciarand, I agree Gin looks really interesting, in fact I just did a second round of benchmarks with it (PR #8), based on PR #3.  About to merge it now! As you will see, Gin did quite well, and I found it just as easy to implement as Martini.
