### ISSUE TITLE
Play errors

### ISSUE THREAD

**Issue by jroper** [mroth/phoenix-showdown#16]
I'm opening this issue as a place to discuss the Play errors.

I assume the OS you're running this on is OSX?  Have you tried Linux?  I don't know what it is, but during my benchmarks I've likewise seen unexplained socket failures on OSX with not just Play, but all java apps that use nio - I think there are big problems with the OSX JDK implementation of the nio APIs that exhibit under load.  The same problems disappear as soon as I run the benchmarks on Linux.

**Comment by mroth** [comment]
I've only tried on OSX, so it sounds like that may indeed be the source of the issue.

@omnibus links some server results in #14 that are on Linux, I presume the socket failures didn't happen there.

**Comment by omnibs** [comment]
Nope, apparently no errors in my runs, although I didn't use any instrumentation to measure that specifically. My `wrk` results just didn't show any socket errors.

I'm considering doing a rerun of all the tests and recording top and iftop for both server and client. It might be useful to see CPU usage patterns. If there's any extra instrumentation you think could help...

**Comment by jroper** [comment]
wrk only outputs information about errors if it encounters errors.  I'm following up a little more with a few people that know a bit more than me about this stuff to see if this is a commonly known issue and whether there are any work arounds or not.

**Comment by jroper** [comment]
Ok, I've found the problem, something to do with kqueue on OSX treating the socket backlog differently to epoll on Linux:

http://www.ybrikman.com/writing/2014/02/18/maxing-out-at-50-concurrent-connections/

Since that post was written, it's now possible to configure this out of the box:

```
./target/universal/stage/bin/play-scala -Dhttp.port=5000 -Dhttp.netty.option.backlog=1024
```

With that, I don't get any socket errors on my macbook:

```
$ wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:5000/showdown"
Running 30s test @ http://127.0.0.1:5000/showdown
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.09ms   12.44ms 261.70ms   96.16%
    Req/Sec    12.49k     2.79k   22.18k    81.92%
  1492976 requests in 30.04s, 2.84GB read
Requests/sec:  49697.97
Transfer/sec:     96.97MB
```

**Comment by jroper** [comment]
I'm going to submit a pull request that upgrades Play 2.4 and also configures this by default.

**Comment by jroper** [comment]
PR submitted here #17.

**Comment by mroth** [comment]
Resolved with the PR.  Thanks!
