### ISSUE TITLE
Better Location For Web Performance Results

### ISSUE THREAD

**Issue by conradwt** [mroth/phoenix-showdown#23]
I definitely appreciate getting the benchmarks on Phoenix against other frameworks but a better place for recording and/or placing these benchmarks can be found at the following link:

https://www.techempower.com/benchmarks/

By doing this, one can put the focus for this repository on Phoenix and Elixir and reduce the amount of work by not support the non-Elixir frameworks.  Furthermore, you'll be comparing Elixir and Phoenix with a much bigger pool of competing technologies.  Just something to consider for this repository.

**Comment by chrismccord** [comment]
Someone has submitted a Phoenix app on the techmeme benchmarks, but it was not well setup or well maintained. The DB pool size was 10x less than the competition, they were doing html csrf for json requests, logging, etc. We sent a PR long ago, but I don't believe it was merged yet

**Comment by conradwt** [comment]
@chrismccord It appears that they have merged all the pull requests regarding Phoenix.
