### ISSUE TITLE
My vote for a Python framework like Django REST

### ISSUE THREAD

**Issue by dogweather** [mroth/phoenix-showdown#24]
I'd really like to see where Python falls into the mix. There are a lot of framework options out there, but Django REST aims itself at this use case, so I think it'd be fair to test it.

**Comment by lucidstack** [comment]
^ agreed! :+1:

**Comment by mroth** [comment]
Hi, thank you for your suggestion.  However. as per the [Contribution Guidelines](https://github.com/mroth/phoenix-showdown/blob/master/CONTRIBUTING.md), this project will not be adding any more new frameworks. Thanks for understanding.
