### ISSUE TITLE
Memory characteristics

### ISSUE THREAD

**Issue by chrisdavies** [mroth/phoenix-showdown#25]
Hey. Thanks so much for putting these together.

I'm debating what platform to use for a memory-constrained side-project, but I noticed you didn't put anything here about how much memory was consumed by each platform. That'd be really helpful.

Thanks again.

**Comment by milose** [comment]
Chris,

Take a look at this: http://blog.onfido.com/using-cpus-elixir-on-raspberry-pi2/

> Even though it was serving a simple html page I am really happy with the results. 540 requests per second on a $35 piece of hardware using on average 90% of the CPU and only 16 Mb memory beats my definition of efficiency!

(Author on using Phoenix / Elixir)

**Comment by chrisdavies** [comment]
Wow. Pretty amazing. Thanks!
