### ISSUE TITLE
Add maru benchmarks

### ISSUE THREAD

**Issue by Trevoke** [mroth/phoenix-showdown#32]
Maru is a port of grape for Elixir: https://github.com/falood/maru

It would be great to have benchmarks for it.

**Comment by mroth** [comment]
Hi, thank you for your suggestion.  However. as per the [Contribution Guidelines](https://github.com/mroth/phoenix-showdown/blob/master/CONTRIBUTING.md), this project will not be adding any more new frameworks. Thanks for understanding.
