### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by ryanmjacobs** [mroth/phoenix-showdown#5]
> I don't find Rails to be as apt a comparison for this use case as Sinatra, since none of it's magic is being used in this example but it hasn't been disabled to it creates a lot of overhead.

This sentence doesn't read very smoothly, and I don't understand what it means by "hasn't been disabled to it creates a lot of overhead".

Maybe something like this would work better?

> I don't find Rails to be as apt a comparison as Sinatra. Since none of it's magic is used in this example, there may be a lot of unnecessary overhead.

**Comment by mroth** [comment]
Thanks! This sentence actually isn't as accurate anymore anyhow with #8 coming up, but I'm cleaning it up anyhow for clarity.

**Comment by ryanmjacobs** [comment]
Thanks for revising that sentence. I can't wait to see #8 completed :grinning:
